spring:
  application:
    name: location-query-microservice
  data:
    mongodb:
      uri: mongodb+srv://nabz:nabz@workshop.rh1jm.mongodb.net/Workshop?retryWrites=true&w=majority
lombok:
  addLombokGeneratedAnnotation: true
