openapi: 3.0.1
info:
  title: Location Query API
  description: API para consultas de actualizaciones de ubicación, permitiendo obtener la última ubicación registrada de un vehículo.
  version: "1.0.0"
servers:
  - url: http://localhost:8080
    description: Servidor local de desarrollo

paths:
  /locations/{vehicleId}:
    get:
      summary: Obtener la ubicación por ID de vehículo
      description: Retorna la última actualización de ubicación registrada para un vehículo específico utilizando su ID.
      operationId: getLocationByVehicleId
      parameters:
        - name: vehicleId
          in: path
          required: true
          schema:
            type: string
            description: ID del vehículo en formato de cadena
            example: "61616c64d4d4f1b2c5f8e7e9"
      responses:
        '200':
          description: Última actualización de ubicación encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationUpdate'
        '404':
          description: No se encontró ninguna actualización de ubicación para el ID de vehículo especificado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No se encontró ninguna actualización de ubicación para el ID de vehículo especificado
        '400':
          description: El ID del vehículo no es válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: El ID del vehículo no es válido
        '500':
          description: Error interno al obtener la ubicación del vehículo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error interno al obtener la ubicación del vehículo

components:
  schemas:
    LocationUpdate:
      type: object
      properties:
        vehicleId:
          type: string
          description: ID del vehículo asociado a la actualización de ubicación
          example: "615b4e64c4f8a7e9b2c5f8d3"
        timestamp:
          type: string
          format: date-time
          description: Marca temporal de la actualización
          example: "2023-01-15T10:00:00Z"
        location:
          type: object
          $ref: '#/components/schemas/Coordinates'
        speed:
          type: number
          format: double
          description: Velocidad del vehículo en km/h
          example: 60.5
        direction:
          type: string
          description: Dirección de movimiento del vehículo
          enum:
            - NORTH
            - EAST
            - SOUTH
            - WEST
          example: "NORTH"
        routeId:
          type: string
          description: ID de la ruta actual
          example: "615b4e64c4f8a7e9b2c5f8d3"
        passengerCount:
          type: integer
          description: Número de pasajeros en el vehículo
          example: 3
        status:
          type: string
          description: Estado operativo del vehículo
          enum:
            - ACTIVE
            - INACTIVE
            - UNDER_MAINTENANCE
          example: "ACTIVE"
        events:
          type: array
          description: Lista de eventos asociados a la actualización de ubicación
          items:
            $ref: '#/components/schemas/Event'

    Coordinates:
      type: object
      properties:
        latitude:
          type: number
          format: double
          description: Latitud de la ubicación
          example: -34.603722
        longitude:
          type: number
          format: double
          description: Longitud de la ubicación
          example: -58.381592

    Event:
      type: object
      properties:
        eventId:
          type: string
          description: ID único del evento
          example: "61616c64d4d4f1b2c5f8e7f0"
        eventType:
          type: string
          description: Tipo de evento registrado
          example: "TRAFFIC_JAM"
        description:
          type: string
          description: Descripción del evento
          example: "Congestión de tráfico en la autopista"
        timestamp:
          type: string
          format: date-time
          description: Marca temporal del evento
          example: "2023-01-15T10:00:00Z"
